(() => {
'use strict';
const W=1280,H=720,FLOOR=620,GRAV=.68,ROUND_FRAMES=99*60;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#game'),ctx=canvas.getContext('2d',{alpha:false});
const screenIds=['title','select','moves','faceoff','fight','result'];
let assetManifest=null,images={},audio={},mode='arcade',selectStep=0,selected=null,selectedOpponent=null,arcadeQueue=[],queueIndex=0,match=null,raf=0,last=0,paused=false;
const CHAR_INFO={
 joe:{label:'Joe',style:'Power Kickboxer',stats:{speed:1.0,power:1.08,def:1.00,ai:.58}},
 jack:{label:'Jack',style:'Fast Technical Striker',stats:{speed:1.10,power:.94,def:.96,ai:.52}},
 john:{label:'John',style:'Pressure Brawler',stats:{speed:.96,power:1.10,def:1.04,ai:.64}},
 justin:{label:'Justin',style:'Counter Specialist',stats:{speed:.94,power:1.02,def:1.10,ai:.70}},
 paul:{label:'Paul',style:'Final Boss Veteran',stats:{speed:1.02,power:1.14,def:1.08,ai:.78}}
};
const CHAR_IDS=['joe','jack','john','justin','paul'];
const held={left:false,right:false,up:false,down:false,lp:false,mp:false,hp:false,lk:false,mk:false,hk:false};
const pressQueue=[];
function show(id){screenIds.forEach(x=>$('#'+x).classList.toggle('active',x===id));}
function playSfx(n,vol=1){const a=audio[n];if(!a)return;const c=a.cloneNode();c.volume=Math.min(1,vol);c.play().catch(()=>{});}
async function loadAll(){assetManifest=await fetch('assets.json').then(r=>r.json());const needed=new Set(assetManifest.allAssets.filter(x=>/\.(png|jpg)$/i.test(x)));await Promise.all([...needed].map(fn=>new Promise(res=>{const im=new Image();im.onload=()=>{images[fn]=im;res()};im.onerror=res;im.src=fn;})));for(const n of ['punch','kick','heavy','block','fireball','tornado','knockdown','win','round','select'])audio[n]=new Audio('sfx_'+n+'.wav');buildRoster();}
function frame(id,semantic,facing=1){const f=assetManifest.characters[id].frames[semantic]||assetManifest.characters[id].frames.stance;const fn=facing===1?f.R:f.L;return images[fn];}
function frameMeta(id,semantic){return assetManifest.characters[id].frames[semantic]||assetManifest.characters[id].frames.stance;}
function buildRoster(){const r=$('#roster');r.innerHTML='';CHAR_IDS.forEach(id=>{const c=document.createElement('button');c.className='roster-card';const im=frame(id,'thumbnail',1);c.innerHTML=`<img src="${im?.src||''}" alt="${CHAR_INFO[id].label}"><h3>${CHAR_INFO[id].label}</h3><p>${CHAR_INFO[id].style}</p>`;c.addEventListener('click',()=>choose(id));r.appendChild(c);});}
function choose(id){playSfx('select');if(selectStep===0){selected=id;if(mode==='arcade'){arcadeQueue=CHAR_IDS.filter(x=>x!==selected); if(selected!=='paul'){arcadeQueue=arcadeQueue.filter(x=>x!=='paul').concat('paul')} queueIndex=0;beginFaceoff(selected,arcadeQueue[0],1);}else{selectStep=1;$('#selectTitle').textContent='SELECT OPPONENT';$('#selectSub').textContent='Choose who to fight';buildRoster();}}else{selectedOpponent=id;if(selectedOpponent===selected){$('#selectSub').textContent='Choose a different opponent';return;}beginFaceoff(selected,selectedOpponent,1);}}
function beginMode(m){mode=m;selectStep=0;selected=selectedOpponent=null;$('#selectTitle').textContent='SELECT YOUR FIGHTER';$('#selectSub').textContent=m==='arcade'?'Choose a coach for the tournament':m==='versus'?'Choose your fighter':'Choose a fighter for training';buildRoster();show('select');}
function beginFaceoff(a,b,stage){show('faceoff');$('#faceA').src=frame(a,'faceoff',1).src;$('#faceB').src=frame(b,'faceoff',-1).src;$('#nameA').textContent=CHAR_INFO[a].label;$('#nameB').textContent=CHAR_INFO[b].label;$('#stageLabel').textContent=mode==='arcade'?`TOURNAMENT STAGE ${stage}`:mode==='training'?'TRAINING MATCH':'EXHIBITION MATCH';setTimeout(()=>startMatch(a,b),1450)}

const ATTACKS={
 lp:{anim:'standingPunch',dur:18,active:[7,11],damage:4,range:62,h:42,y:112,sfx:'punch'},
 mp:{anim:'standingPunch',dur:22,active:[8,13],damage:6,range:76,h:46,y:112,sfx:'punch'},
 hp:{anim:'standingPunch',dur:27,active:[10,16],damage:9,range:88,h:50,y:112,sfx:'heavy',stun:18},
 lk:{anim:'standingKickBody',dur:20,active:[8,13],damage:5,range:78,h:42,y:125,sfx:'kick'},
 mk:{anim:'standingKickBody',dur:24,active:[9,15],damage:7,range:100,h:42,y:122,sfx:'kick'},
 hk:{anim:'standingKickHead',dur:29,active:[11,17],damage:10,range:110,h:50,y:92,sfx:'heavy',knock:true},
 crouchP:{anim:'crouchPunch',dur:19,active:[7,12],damage:5,range:68,h:36,y:72,sfx:'punch'},
 upper:{anim:'crouchUppercut',dur:27,active:[9,17],damage:10,range:76,h:105,y:112,sfx:'heavy',knock:true},
 crouchK:{anim:'crouchKick',dur:21,active:[8,14],damage:6,range:84,h:30,y:34,sfx:'kick',low:true},
 sweep:{anim:'crouchTrip',dur:29,active:[10,17],damage:9,range:112,h:28,y:24,sfx:'heavy',low:true,knock:true},
 jumpP:{anim:'jumpPunch',dur:18,active:[4,15],damage:6,range:70,h:48,y:106,sfx:'punch'},
 jumpK:{anim:'jumpKick',dur:20,active:[5,17],damage:8,range:102,h:44,y:105,sfx:'kick',knock:false},
 thrust:{anim:'thrustSideKick',dur:28,active:[9,18],damage:9,range:122,h:44,y:112,sfx:'heavy',push:8},
 backKick:{anim:'backKick',dur:28,active:[9,18],damage:8,range:105,h:46,y:114,sfx:'kick'},
 tornado:{anim:'tornadoKick',dur:42,active:[9,33],damage:4,range:112,h:80,y:100,sfx:'tornado',multi:3,move:4.7},
 rising:{anim:'crouchUppercut',dur:36,active:[7,18],damage:11,range:80,h:120,y:126,sfx:'heavy',knock:true,rise:true},
 rush:{anim:'thrustSideKick',dur:32,active:[9,22],damage:10,range:110,h:54,y:112,sfx:'heavy',move:8},
 fireball:{anim:'fireball',dur:33,active:[13,15],damage:8,projectile:true,sfx:'fireball'},
 super:{anim:'fireball',dur:44,active:[15,17],damage:16,projectile:true,super:true,sfx:'fireball'},
 throw:{anim:'standingPunch',dur:40,active:[7,11],damage:12,range:62,h:100,y:94,sfx:'heavy',throw:true,knock:true}
};
const ANIMS={
 idle:['stance','stance'],walk:['stance','standingPunch','stance'],back:['stance','standingBlock','stance'],block:['standingBlock'],crouch:['crouch'],crouchBlock:['crouchBlock'],jump:['jump'],
 standingPunch:['stance','standingPunch','standingPunch','stance'],standingKickBody:['stance','standingKickBody','standingKickBody','stance'],standingKickHead:['stance','standingKickHead','standingKickHead','stance'],
 crouchPunch:['crouch','crouchPunch','crouchPunch','crouch'],crouchUppercut:['crouch','crouchUppercut','crouchUppercut','stance'],crouchKick:['crouch','crouchKick','crouchKick','crouch'],crouchTrip:['crouch','crouchTrip','crouchTrip','crouch'],
 jumpPunch:['jump','jumpPunch','jumpPunch','jump'],jumpKick:['jump','jumpKick','jumpKick','jump'],thrustSideKick:['stance','thrustSideKick','thrustSideKick','stance'],backKick:['stance','backKick','backKick','stance'],
 tornadoKick:['stance','tornadoKick','tornadoKick','tornadoKick','stance'],fireball:['stance','fireball','fireball','stance'],hitHigh:['hitHigh'],hitLow:['hitLow'],hitAir:['hitAir'],layGround:['layGround'],gettingUp:['gettingUp','stance'],defeated:['defeated'],
 winDown:['winnerDown'],winRaised:['winnerRaised'],celebration:['celebration']
};
class Projectile{constructor(owner,superShot=false){this.owner=owner;this.x=owner.x+owner.facing*80;this.y=owner.y-118;this.vx=owner.facing*(superShot?10.5:7.6);this.r=superShot?31:22;this.damage=superShot?16:8;this.superShot=superShot;this.live=true}update(){this.x+=this.vx;if(this.x<-60||this.x>1340)this.live=false}draw(){ctx.save();let g=ctx.createRadialGradient(this.x,this.y,2,this.x,this.y,this.r);g.addColorStop(0,'#fff');g.addColorStop(.25,this.superShot?'#fff05d':'#c7f2ff');g.addColorStop(.58,this.superShot?'#ff7a22':'#28a7ff');g.addColorStop(1,'rgba(0,80,255,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(this.x,this.y,this.r,0,Math.PI*2);ctx.fill();ctx.restore()}}
class Fighter{
 constructor(id,x,facing,cpu=false){this.id=id;this.info=CHAR_INFO[id];this.x=x;this.y=FLOOR;this.vx=0;this.vy=0;this.facing=facing;this.cpu=cpu;this.health=100;this.meter=0;this.wins=0;this.state='idle';this.stateT=0;this.attack=null;this.hitIds=new Set();this.inv=0;this.inputHist=[];this.charge=0;this.cpuCD=0;this.combo=0;this.comboT=0;this.celebrateT=0;this.prevSemantic='stance';const meta=frameMeta(id,'stance');this.scale=242/meta.h;}
 grounded(){return this.y>=FLOOR-.1} hurtbox(){let crouch=['crouch','crouchBlock','crouchPunch','crouchKick','crouchTrip','crouchUppercut'].includes(this.state);let h=crouch?126:184;return{x:this.x-42,y:this.y-h,w:84,h}}
 setState(s){if(this.state!==s){this.state=s;this.stateT=0}}
 dirCode(inp){let h=(inp.right?1:0)-(inp.left?1:0);if(this.facing<0)h=-h;let v=(inp.down?1:0)-(inp.up?1:0);return({'0,0':5,'1,0':6,'-1,0':4,'0,1':2,'0,-1':8,'1,1':3,'-1,1':1,'1,-1':9,'-1,-1':7})[`${h},${v}`]||5}
 record(inp){let c=this.dirCode(inp),t=performance.now(),last=this.inputHist.at(-1);if(!last||last.c!==c){this.inputHist.push({c,t});if(this.inputHist.length>22)this.inputHist.shift()}}
 motion(seq,age=700){let now=performance.now(),a=this.inputHist.filter(x=>now-x.t<age).map(x=>x.c),p=seq.length-1;for(let i=a.length-1;i>=0&&p>=0;i--)if(a[i]===seq[p])p--;return p<0}
 canAct(){return !this.attack&&!['hitHigh','hitLow','hitAir','layGround','gettingUp','defeated','winDown','winRaised','celebration'].includes(this.state)}
 startAttack(key){const d=ATTACKS[key];if(!d||!this.canAct())return;this.attack={key,d,t:0,hits:0,spawned:false};this.state=d.anim;this.stateT=0;if(d.rise){this.vy=-10.5;this.vx=this.facing*2.5}if(d.move)this.vx=this.facing*d.move;playSfx(d.sfx,key==='hp'||key==='hk'?1:.75)}
 press(btn,inp){if(!this.canAct())return;let qcf=this.motion([2,3,6]),qcb=this.motion([2,1,4]),dp=this.motion([6,2,3]),doubleQ=this.motion([2,3,6,2,3,6],950);if(btn==='throw'){this.startAttack('throw');return}if(btn==='hp'&&doubleQ&&this.meter>=100){this.meter=0;this.startAttack('super');return}if(['lp','mp','hp'].includes(btn)&&qcf){this.startAttack('fireball');return}if(['lk','mk','hk'].includes(btn)&&qcb){this.startAttack('tornado');return}if(btn==='hp'&&dp){this.startAttack('rising');return}let forward=this.facing>0?inp.right:inp.left,back=this.facing>0?inp.left:inp.right;if(['lk','mk','hk'].includes(btn)&&this.charge>45&&forward){this.charge=0;this.startAttack('rush');return}if(!this.grounded()){this.startAttack(btn[0]==='l'||btn[0]==='m'||btn[0]==='h'? (btn.endsWith('p')?'jumpP':'jumpK') : 'jumpP');return}if(inp.down){if(btn==='hp')this.startAttack('upper');else if(btn==='hk')this.startAttack('sweep');else if(btn.endsWith('p'))this.startAttack('crouchP');else this.startAttack('crouchK');return}if(back&&btn==='hk'){this.startAttack('backKick');return}if(forward&&(btn==='mk'||btn==='hk')){this.startAttack('thrust');return}this.startAttack(btn)}
 isBlocking(sourceFacing,low){let inp=this.lastInput||{};let away=this.facing>0?inp.left:inp.right;if(!away)return false;return low?!!inp.down:!inp.down&&this.grounded()}
 receive(dmg,sourceFacing,{low=false,knock=false,throwing=false}={}){if(this.inv>0||this.state==='defeated')return false;if(!throwing&&this.isBlocking(sourceFacing,low)){this.health=Math.max(0,this.health-dmg*.14);this.meter=Math.min(100,this.meter+4);this.setState(low?'crouchBlock':'block');this.stateT=0;this.vx=sourceFacing*2.5;playSfx('block');return true}this.health=Math.max(0,this.health-dmg/this.info.stats.def);this.meter=Math.min(100,this.meter+8);if(this.health<=0){this.attack=null;this.setState('defeated');this.vx=sourceFacing*5.5;this.vy=-7.5;playSfx('knockdown');return true}if(knock){this.attack=null;this.setState('hitAir');this.vx=sourceFacing*5.5;this.vy=-9.5;playSfx('heavy');}else{this.attack=null;this.setState(low?'hitLow':'hitHigh');this.vx=sourceFacing*3.5;playSfx('punch');}return true}
 cpuInput(enemy){const o={left:false,right:false,up:false,down:false};let dist=enemy.x-this.x,abs=Math.abs(dist),toward=dist>0?'right':'left',away=dist>0?'left':'right';if(enemy.attack&&abs<150&&Math.random()<.09){o[away]=true;if(Math.random()<.35)o.down=true;return o}if(abs>155)o[toward]=true;else if(abs<78)o[away]=Math.random()<.35;this.cpuCD--;if(this.cpuCD<=0&&this.canAct()){let r=Math.random(),a=this.info.stats.ai;this.cpuCD=22+Math.random()*34*(1-a+.35);if(abs<145){if(r<.16){o.down=true;pressQueue.push({who:this,btn:'hk'})}else if(r<.33)pressQueue.push({who:this,btn:'hp'});else if(r<.52)pressQueue.push({who:this,btn:'mk'});else if(r<.67){this.inputHist.push({c:2,t:performance.now()-130},{c:1,t:performance.now()-90},{c:4,t:performance.now()-25});pressQueue.push({who:this,btn:'hk'})}else if(r<.83){this.inputHist.push({c:2,t:performance.now()-130},{c:3,t:performance.now()-90},{c:6,t:performance.now()-25});pressQueue.push({who:this,btn:'hp'})}else pressQueue.push({who:this,btn:'throw'});}else if(r<.28){this.inputHist.push({c:2,t:performance.now()-120},{c:3,t:performance.now()-80},{c:6,t:performance.now()-20});pressQueue.push({who:this,btn:'hp'})}}
 return o}
 update(inp,enemy){if(this.inv>0)this.inv--;if(this.comboT>0)this.comboT--;else this.combo=0;if(this.cpu)inp=this.cpuInput(enemy);this.lastInput=inp;this.record(inp);let back=this.facing>0?inp.left:inp.right;if(back)this.charge++;else this.charge=0;if(!this.grounded())this.vy+=GRAV;if(this.attack){this.attack.t++;this.stateT++;let d=this.attack.d;if(d.move)this.vx=this.facing*d.move*(1-this.attack.t/d.dur*.45);if(d.rise&&this.attack.t<18)this.vy=Math.min(this.vy,-2);if(d.projectile&&!this.attack.spawned&&this.attack.t>=d.active[0]){match.projectiles.push(new Projectile(this,d.super));this.attack.spawned=true}if(!d.projectile&&this.attack.t>=d.active[0]&&this.attack.t<=d.active[1])this.resolveHit(enemy);if(this.attack.t>=d.dur){this.attack=null;if(this.grounded())this.setState(inp.down?'crouch':'idle');else this.setState('jump')}}else if(this.canAct()){
 if(inp.up&&this.grounded()){this.vy=-12.2;this.setState('jump')}else if(inp.down)this.setState('crouch');else{let toward=this.facing>0?inp.right:inp.left;if(inp.left||inp.right){this.x+=(inp.right?1:-1)*4.0*this.info.stats.speed;this.setState(toward?'walk':'back')}else this.setState('idle')}}
 if(['hitHigh','hitLow','block','crouchBlock'].includes(this.state)){this.stateT++;if(this.stateT>16)this.setState(this.lastInput?.down?'crouch':'idle')}if(this.state==='hitAir'){this.stateT++;if(this.grounded()&&this.stateT>5){this.setState('layGround');this.stateT=0}}else if(this.state==='layGround'){this.stateT++;if(this.stateT>38&&this.health>0){this.setState('gettingUp');this.stateT=0;this.inv=35}}else if(this.state==='gettingUp'){this.stateT++;if(this.stateT>28)this.setState('idle')}
 this.x+=this.vx;this.y+=this.vy;this.vx*=.78;if(this.y>=FLOOR){this.y=FLOOR;this.vy=0;if(this.state==='jump')this.setState('idle')}this.x=Math.max(90,Math.min(1190,this.x));}
 resolveHit(enemy){let d=this.attack.d;if(d.multi&&this.attack.hits>=d.multi)return;if(!d.multi&&this.attack.hits>0)return;let hb=this.hitbox(d),eb=enemy.hurtbox();if(intersect(hb,eb)){if(enemy.receive(d.damage*this.info.stats.power,this.facing,{low:d.low,knock:d.knock,throwing:d.throw})){this.attack.hits++;this.meter=Math.min(100,this.meter+(d.damage>8?12:8));this.combo++;this.comboT=50;match.score+=Math.round(d.damage*100*this.combo);if(d.throw){enemy.vx=this.facing*7;enemy.vy=-8}}}}
 hitbox(d){let cx=this.x+this.facing*(d.range/2+40);return{x:cx-d.range/2,y:this.y-d.y,w:d.range,h:d.h}}
 semantic(){if(this.attack)return this.attack.d.anim;return this.state}
 draw(){let semantic=this.semantic(),seq=ANIMS[semantic]||ANIMS.idle,phase=0;if(this.attack)phase=Math.min(seq.length-1,Math.floor((this.attack.t/this.attack.d.dur)*seq.length));else if(['walk','back'].includes(this.state))phase=Math.floor(performance.now()/130)%seq.length;else if(['gettingUp'].includes(this.state))phase=Math.min(seq.length-1,Math.floor(this.stateT/14));let sem=seq[phase]||'stance';let img=frame(this.id,sem,this.facing),meta=frameMeta(this.id,sem);if(!img)return;let scale=this.scale, dw=img.width*scale,dh=img.height*scale;let y=this.y-dh+16;if(sem==='layGround'||sem==='defeated')y=this.y-dh+10;ctx.save();ctx.drawImage(img,this.x-dw/2,y,dw,dh);ctx.restore();}
}
function intersect(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function startMatch(a,b){show('fight');attemptFullscreen();match={p1:new Fighter(a,360,1,false),p2:new Fighter(b,920,-1,mode!=='training'),timer:ROUND_FRAMES,round:1,projectiles:[],score:0,roundOver:false,matchOver:false,banner:'ROUND 1',bannerT:80};if(mode==='training'){match.p2.cpu=false;match.p2.health=100;match.training=true}paused=false;$('#pauseOverlay').classList.add('hidden');cancelAnimationFrame(raf);last=0;playSfx('round');raf=requestAnimationFrame(loop)}
function attemptFullscreen(){let el=document.documentElement;if(el.requestFullscreen)el.requestFullscreen().catch(()=>{});if(screen.orientation?.lock)screen.orientation.lock('landscape').catch(()=>{})}
function loop(t){let dt=Math.min(2,(t-last||16.7)/16.7);last=t;if(!paused){update(dt);draw()}raf=requestAnimationFrame(loop)}
function update(dt){if(!match||match.matchOver)return;let p1inp={...held};for(const q of pressQueue.splice(0)){let f=q.who||match.p1;f.press(q.btn,f.lastInput||p1inp)}match.p1.update(p1inp,match.p2);match.p2.update({},match.p1);match.p1.facing=match.p1.x<=match.p2.x?1:-1;match.p2.facing=-match.p1.facing;pushApart(match.p1,match.p2);for(const p of match.projectiles){p.update();let tar=p.owner===match.p1?match.p2:match.p1;if(p.live&&intersect({x:p.x-p.r,y:p.y-p.r,w:p.r*2,h:p.r*2},tar.hurtbox())){tar.receive(p.damage,p.owner.facing,{knock:p.superShot});p.live=false;match.score+=p.damage*120}}match.projectiles=match.projectiles.filter(p=>p.live);if(match.bannerT>0)match.bannerT-=dt;if(!match.training&&!match.roundOver){match.timer-=dt;if(match.timer<=0||match.p1.health<=0||match.p2.health<=0)roundEnd()}}
function pushApart(a,b){let d=b.x-a.x,min=82;if(Math.abs(d)<min){let push=(min-Math.abs(d))/2;if(d>=0){a.x-=push;b.x+=push}else{a.x+=push;b.x-=push}}}
function roundEnd(){match.roundOver=true;let p=match.p1,e=match.p2;if(p.health===e.health)e.health=Math.max(0,e.health-1);let win=p.health>e.health;if(win)p.wins++;else e.wins++;match.banner=win?`${p.info.label} WINS`:`${e.info.label} WINS`;match.bannerT=95;if(win){p.setState('winDown');setTimeout(()=>p.setState('winRaised'),450);setTimeout(()=>p.setState('celebration'),900);playSfx('win')}else{e.setState('winDown');setTimeout(()=>e.setState('winRaised'),450);setTimeout(()=>e.setState('celebration'),900)}setTimeout(()=>{if(p.wins>=2||e.wins>=2)finishMatch(p.wins>=2);else nextRound()},1500)}
function nextRound(){let a=match.p1.id,b=match.p2.id,pw=match.p1.wins,ew=match.p2.wins,score=match.score;match={p1:new Fighter(a,360,1,false),p2:new Fighter(b,920,-1,mode!=='training'),timer:ROUND_FRAMES,round:pw+ew+1,projectiles:[],score,roundOver:false,matchOver:false,banner:`ROUND ${pw+ew+1}`,bannerT:80};match.p1.wins=pw;match.p2.wins=ew;playSfx('round')}
function finishMatch(playerWon){cancelAnimationFrame(raf);match.matchOver=true;let id=playerWon?match.p1.id:match.p2.id;$('#resultImg').src=frame(id,playerWon?'celebration':'winnerRaised',1).src;if(playerWon){$('#resultTitle').textContent='VICTORY';if(mode==='arcade'&&queueIndex<arcadeQueue.length-1){$('#resultText').textContent=`${match.p2.info.label} is defeated. Score ${match.score.toLocaleString()}.`;$('#continueBtn').textContent='NEXT FIGHT';$('#continueBtn').onclick=()=>{queueIndex++;beginFaceoff(selected,arcadeQueue[queueIndex],queueIndex+1)}}else{$('#resultText').textContent=mode==='arcade'?`You are the FKBC Dojo Masters champion. Final score ${match.score.toLocaleString()}.`:`${match.p1.info.label} wins the match.`;$('#continueBtn').textContent='FIGHT AGAIN';$('#continueBtn').onclick=()=>beginMode(mode)}}else{$('#resultTitle').textContent='DEFEAT';$('#resultText').textContent=`${match.p2.info.label} wins. Return to character select and try again.`;$('#continueBtn').textContent='REMATCH';$('#continueBtn').onclick=()=>beginFaceoff(selected,mode==='arcade'?arcadeQueue[queueIndex]:selectedOpponent,queueIndex+1)}show('result')}
function draw(){ctx.drawImage(images['arena.jpg'],0,0,W,H);ctx.fillStyle='rgba(0,0,0,.12)';ctx.fillRect(0,0,W,H);drawHUD();ctx.fillStyle='rgba(0,0,0,.28)';for(const f of [match.p1,match.p2]){ctx.beginPath();ctx.ellipse(f.x,FLOOR-7,58,12,0,0,Math.PI*2);ctx.fill()}match.projectiles.forEach(p=>p.draw());[match.p1,match.p2].forEach(f=>f.draw());if(match.p1.combo>1&&match.p1.comboT>0){ctx.font='900 34px Arial';ctx.lineWidth=7;ctx.strokeStyle='#000';ctx.fillStyle='#ffd23d';ctx.strokeText(`${match.p1.combo} HIT COMBO`,35,190);ctx.fillText(`${match.p1.combo} HIT COMBO`,35,190)}if(match.bannerT>0){ctx.textAlign='center';ctx.font='900 62px Impact';ctx.lineWidth=9;ctx.strokeStyle='#000';ctx.fillStyle='#ffcf35';ctx.strokeText(match.banner,640,325);ctx.fillText(match.banner,640,325);ctx.textAlign='left'}}
function drawHUD(){ctx.fillStyle='#090e17d9';ctx.fillRect(0,0,W,105);drawPortraitHUD(match.p1,16,12,false);drawPortraitHUD(match.p2,1194,12,true);ctx.font='900 25px Arial';ctx.fillStyle='#fff';ctx.textAlign='left';ctx.fillText(match.p1.info.label.toUpperCase(),96,34);ctx.textAlign='right';ctx.fillText(match.p2.info.label.toUpperCase(),1184,34);bar(96,46,392,24,match.p1.health/100,'#ffe05b','#ef244f',false);bar(792,46,392,24,match.p2.health/100,'#ffe05b','#ef244f',true);bar(96,78,300,12,match.p1.meter/100,'#5ee8ff','#1677ff',false);bar(884,78,300,12,match.p2.meter/100,'#5ee8ff','#1677ff',true);ctx.textAlign='center';ctx.font='900 48px Impact';ctx.fillStyle='#ffd43d';ctx.strokeStyle='#000';ctx.lineWidth=6;ctx.strokeText(match.training?'∞':Math.max(0,Math.ceil(match.timer/60)),640,57);ctx.fillText(match.training?'∞':Math.max(0,Math.ceil(match.timer/60)),640,57);ctx.font='900 18px Arial';ctx.fillStyle='#fff';ctx.fillText('K.O.',640,20);ctx.textAlign='left';dots(505,84,match.p1.wins,false);dots(748,84,match.p2.wins,true)}
function drawPortraitHUD(f,x,y,flip){let im=frame(f.id,'thumbnail',flip?-1:1);ctx.save();ctx.beginPath();ctx.rect(x,y,70,70);ctx.clip();let s=Math.min(70/im.width,70/im.height);ctx.drawImage(im,x+(70-im.width*s)/2,y+(70-im.height*s)/2,im.width*s,im.height*s);ctx.restore()}
function bar(x,y,w,h,p,a,b,rev){ctx.fillStyle='#1b2635';ctx.fillRect(x,y,w,h);let ww=w*Math.max(0,Math.min(1,p));let g=ctx.createLinearGradient(x,0,x+w,0);g.addColorStop(0,a);g.addColorStop(1,b);ctx.fillStyle=g;ctx.fillRect(rev?x+w-ww:x,y,ww,h);ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.strokeRect(x,y,w,h)}function dots(x,y,n,rev){for(let i=0;i<2;i++){ctx.fillStyle=i<n?'#ffd43d':'#263649';ctx.beginPath();ctx.arc(x+(rev?-i:i)*28,y,9,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.stroke()}}

// UI
$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>{playSfx('select');beginMode(b.dataset.mode)}));$('#howBtn').onclick=()=>show('moves');$$('[data-back]').forEach(b=>b.onclick=()=>show('title'));$$('[data-home]').forEach(b=>b.onclick=()=>{cancelAnimationFrame(raf);show('title')});$('#pauseBtn').onclick=()=>togglePause();$('#resumeBtn').onclick=()=>togglePause(false);$('#quitBtn').onclick=()=>{paused=false;cancelAnimationFrame(raf);show('title')};function togglePause(force){paused=force===undefined?!paused:force;$('#pauseOverlay').classList.toggle('hidden',!paused)}
const keymap={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'};const atkKeys={KeyJ:'lp',KeyK:'mp',KeyL:'hp',KeyU:'lk',KeyI:'mk',KeyO:'hk',KeyT:'throw'};
addEventListener('keydown',e=>{if(e.code==='KeyP'){togglePause();return}if(keymap[e.code]){held[keymap[e.code]]=true;e.preventDefault()}if(atkKeys[e.code]&&!e.repeat){pressQueue.push({btn:atkKeys[e.code]});e.preventDefault()}});addEventListener('keyup',e=>{if(keymap[e.code]){held[keymap[e.code]]=false;e.preventDefault()}});
$$('[data-dir]').forEach(b=>{let k=b.dataset.dir;const d=e=>{held[k]=true;b.classList.add('pressed');e.preventDefault()},u=e=>{held[k]=false;b.classList.remove('pressed');e.preventDefault()};b.addEventListener('pointerdown',d);['pointerup','pointercancel','pointerleave'].forEach(x=>b.addEventListener(x,u))});$$('[data-atk]').forEach(b=>{const d=e=>{pressQueue.push({btn:b.dataset.atk});b.classList.add('pressed');e.preventDefault()},u=e=>{b.classList.remove('pressed');e.preventDefault()};b.addEventListener('pointerdown',d);['pointerup','pointercancel','pointerleave'].forEach(x=>b.addEventListener(x,u))});$('#throwBtn').addEventListener('pointerdown',e=>{pressQueue.push({btn:'throw'});e.preventDefault()});
let gpPrev=[];function pollGamepad(){let gp=navigator.getGamepads?.()[0];if(gp&&match&&$('#fight').classList.contains('active')){let x=gp.axes[0]||0,y=gp.axes[1]||0;held.left=x<-.35;held.right=x>.35;held.up=y<-.45;held.down=y>.45;let map=['lp','mp','hp','lk','mk','hk'];map.forEach((k,i)=>{let on=!!gp.buttons[i]?.pressed;if(on&&!gpPrev[i])pressQueue.push({btn:k});gpPrev[i]=on})}requestAnimationFrame(pollGamepad)}pollGamepad();
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});loadAll().then(()=>show('title'));
})();
